In [1]:
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file("key.json") # lokalizacja pobranego klucza z punktu 1.4.

client = bigquery.Client(credentials=credentials, project=credentials.project_id)

In [2]:
query = """
SELECT *
FROM `bigquery-public-data.noaa_gsod.gsod2020`
    limit 10
"""

query_job = client.query(query)
query_result = query_job.result()
df = query_result.to_dataframe()

In [3]:
df

,stn,wban,date,year,mo,da,temp,count_temp,dewp,count_dewp,...,flag_min,prcp,flag_prcp,sndp,fog,rain_drizzle,snow_ice_pellets,hail,thunder,tornado_funnel_cloud
0,010030,99999,2020-10-12,2020,10,12,27.0,4,20.5,4,...,None,0.0,I,999.9,0,0,0,0,0,0
1,010350,99999,2020-11-08,2020,11,08,27.9,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
2,010370,99999,2020-12-19,2020,12,19,22.3,4,16.6,4,...,None,0.0,I,999.9,0,0,0,0,0,0
3,010420,99999,2020-03-03,2020,03,03,21.5,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
4,010420,99999,2020-02-18,2020,02,18,23.9,4,9999.9,0,...,*,0.0,I,999.9,0,0,0,0,0,0
5,010430,99999,2020-01-15,2020,01,15,29.2,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
6,010430,99999,2020-02-01,2020,02,01,18.9,4,9999.9,0,...,*,0.0,I,999.9,0,0,0,0,0,0
7,010430,99999,2020-01-17,2020,01,17,25.1,4,9999.9,0,...,*,0.0,I,999.9,0,0,0,0,0,0
8,010430,99999,2020-03-18,2020,03,18,29.5,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
9,010430,99999,2020-04-03,2020,04,03,24.0,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0

# Misja dodatkowa 3

### 3.1. Sprawdź, ile jest zapisanych wierszy z danymi.

In [4]:
query3_1 = """
    SELECT COUNT(*) AS count_rows
    FROM `bigquery-public-data.noaa_gsod.gsod2020`
"""

df_3_1 = client.query(query3_1).to_dataframe()
df_3_1['count_rows'].loc[0]

np.int64(4119205)

### 3.2. Sprawdź, ile krajów jest uwzględnionych w danych.

In [5]:
query3_2 = """
        SELECT COUNT(DISTINCT country) as country_count
        FROM `bigquery-public-data.noaa_gsod.gsod2020` AS gsod
                 INNER JOIN `bigquery-public-data.noaa_gsod.stations` AS st
                            ON st.usaf = gsod.stn and gsod.wban = st.wban
        """

df_3_2= client.query(query3_2).to_dataframe()
df_3_2['country_count'].loc[0]

np.int64(236)

### 3.3. Sprawdź, w jaki sposób zapisywane są dzienne informacje dla poszczególnych lokalizacji.

In [6]:
query = """
SELECT *
FROM `bigquery-public-data.noaa_gsod.gsod2020`
    limit 10
"""

query_job = client.query(query)
query_result = query_job.result()
df = query_result.to_dataframe()
df

,stn,wban,date,year,mo,da,temp,count_temp,dewp,count_dewp,...,flag_min,prcp,flag_prcp,sndp,fog,rain_drizzle,snow_ice_pellets,hail,thunder,tornado_funnel_cloud
0,010030,99999,2020-10-12,2020,10,12,27.0,4,20.5,4,...,None,0.0,I,999.9,0,0,0,0,0,0
1,010350,99999,2020-11-08,2020,11,08,27.9,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
2,010370,99999,2020-12-19,2020,12,19,22.3,4,16.6,4,...,None,0.0,I,999.9,0,0,0,0,0,0
3,010420,99999,2020-03-03,2020,03,03,21.5,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
4,010420,99999,2020-02-18,2020,02,18,23.9,4,9999.9,0,...,*,0.0,I,999.9,0,0,0,0,0,0
5,010430,99999,2020-01-15,2020,01,15,29.2,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
6,010430,99999,2020-02-01,2020,02,01,18.9,4,9999.9,0,...,*,0.0,I,999.9,0,0,0,0,0,0
7,010430,99999,2020-01-17,2020,01,17,25.1,4,9999.9,0,...,*,0.0,I,999.9,0,0,0,0,0,0
8,010430,99999,2020-03-18,2020,03,18,29.5,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0
9,010430,99999,2020-04-03,2020,04,03,24.0,4,9999.9,0,...,None,0.0,I,999.9,0,0,0,0,0,0

 0.   stn - numer identyfikacyjny stacji
 1.   wban - numer Weather Bureau Air Force Navy, używany historycznie przez amerykańskie biura pogodowe oraz wojsko
 2.   date - data obserwacji
 3.   year - rok obserwacji
 4.   mo   - miesiąc obserwacji
 5.   da   - dzień obserwacji
 6.   temp - średnia temperatura dobowa w stopniach Fahrenheita, zaokrąglona do części dziesiętnych *
 7.   count_temp  - liczba obserwacji
 8.   dewp - średni, dobowy punkt rosy w stopniach Fahrenheita, zaokrąglony do części dziesiętnych *
 9.   count_dewp  - liczba obserwacji
 10.  slp - średnie ciśnienie nad poziomem morza (mbar), zaokrąglone do części dziesiętnych *
 11.  count_slp - liczba obserwacji
 12.  stp - średnie ciśnienie na poziomie stacji pogodowej (mbar), zaokrąglone do części dziesiętnych *
 13.  count_stp - liczba obserwacji
 14.  visib - średnia widoczność w milach, zaokrąglona do części dziesiętnych **
 15.  count_visib   - liczba obserwacji
 16.  wdsp - średnia predkość wiatru w węzłach, zaokrąglona do części dziesiętnych **
 17.  count_wdsp   - liczba obserwacji
 18.  mxpsd - maksymalna, utrzymująca się prędkość wiatru w węzłach, zaokrąglona do części dziesiętnych **
 19.  gust - maksymalna prędkość podmuchu wiatru w węzłach, zaokrąglona do części dziesiętnych **
 20.  max - maksymalna temperatura zarejestrowana dla danego kraju i regionu w stopniach Fahrenheita, zaokrąglona do części dziesiętnych *
 21.  flag_max - wskaźnik informujący czy maksymalna temperatura została pobrana z raportu, czy wyliczona z danych godzinowych
 22.  min - minimalna temperatura zarejestrowana dla danego kraju i regionu w stopniach Fahrenheita, zaokrąglona do części dziesiętnych *
 23.  flag_min - wskaźnik informujący czy maksymalna temperatura została pobrana z raportu, czy wyliczona z danych godzinowych
 24.  prcp - całkowita suma opadów (również roztopiony śnieg) w calach, zaokrąglone do części setnych  ***
 25.  flag_prcp - wskaźnik informujący ilości raportów zgłoszonych w ciągu dnia
 - A - 1 raport 6-godzinnej ilości opadów
 - B - suma 2 raportów 6-godzinnych
 - C - suma 3 raportów 6-godzinnych
 - D - suma 4 raportów 6-godzinnych
 - E - 1 raport o 12-godzinnej ilości opadów
 - F - suma 2 raportów 12-godzinnych
 - G - 1 raport o 24-godzinnej ilości opadów
 26.  sndp - grbość pokrywy śnieżnej w calach, ostatni pomiar w ciągu dnia, jeżeli wykonano więcej niż 1 **
 27.  fog - wskaźnik informujący o występowaniu mgły w ciągu dnia
 28.  rain_drizzle - wskaźnik informujący o występowaniu mżawki w ciągu dnia
 29.  snow_ice_pellets - wskaźnik informujący o występowaniu krup śnieżnych bądź lodowych (mieszanka śniegu i lodu) w ciągu dnia
 30.  hail - wskaźnik informujący o występowaniu gradu w ciągu dnia
 31.  thunder - wskaźnik informujący o wystąpieniu burzy w ciągu dnia
 32.  tornado_funnel_cloud - wskaźnik informujący o wystąpieniu tornada bądź leja kondensacyjnego w ciągu dnia

\* brakujące wartości są zastąpione przez 9999.9<br>
\** brakujące wartości są zastąpione przez 999.9<br>
\*** brakujące wartości są zastąpione przez 99.99<br>

### 3.4. Sprawdź, w jaki sposób zapisywane są wartości liczbowe.

wartości pomiarów zapisywane są w postaci liczb zmiennoprzecinkowych (float) zaokrąglone do pierwszego miejsca po przecinku, natomiast wartości opisyjące liczbe pomiarów są liczbami całkowitymi (integer)

### 3.5. Sprawdź, jaki przedział czasowy jest uwzględniony w danych. Dodatkowo porównaj zakresy czasowe dla różnych zmiennych pogodowych, takich jak temperatura i opady.

Pomiary są prowadzone w skali roku, każdy wpis obejmuje jeden dzień.<br>
Ilość pomiarów danych dotyczących temperatury, punktu rosy, ciśnienia, widoczności i prędkości wiatru w ciągu dnia są opisane przez wartości count_x (gdzie x oznacza wymienione wcześniej parametry).

Przedział czasowy danych dotyczących opadów jest określony przez wartość flag_prcp:
 - A - 1 raport 6-godzinnej ilości opadów
 - B - suma 2 raportów 6-godzinnych
 - C - suma 3 raportów 6-godzinnych
 - D - suma 4 raportów 6-godzinnych
 - E - 1 raport o 12-godzinnej ilości opadów
 - F - suma 2 raportów 12-godzinnych
 - G - 1 raport o 24-godzinnej ilości opadów

### 3.6. Sprawdź więcej informacji (co najmniej 5 różnych) o danych pogodowych. W tym celu nie wykonuj żadnych dodatkowych obliczeń. Wyniki przedstaw w formie krótkiego raportu.

### Raport
1. **Imperialny system miar**:
- używane jednostki to:
    - stopnie Fahrenheita dla temperatury
    - mile dla odległości
    - węzły dla prędkości wiatru
    - cale dla opadów i grubości pokrywy śnieżnej
2. Występowanie ekstremalnych zjawisk pogodowych reprezentowane jest przez wartości 0 i 1 (0 - nie wystąpiło, 1 - wystąpiło)
3. Powielenie danych dotyczących zapisu daty. Występuje zarówno pełna data, jak i rok, miesiąc oraz dzień
4. Raportowanie grubości pokryty śnieżnej. W przypadku gdy wykonano więcej niż jedne pomiar w ciągu dnia, wpisywany jest ostatni wynik. Większośc stacji brak pokrywy śnieżnej raportuje jako 999.9
5. Kolumny flang_min i flag_max informują o tym, w jaki sposób została dostarczona informacja o wartości ekstremalnej. * oznacza, że wartość została obliczona, a null, że została pobrana z raportu stacji

# Część 4

### Przeanalizuj poniższe przypadki. Zastanów się, jakie dane potrzebujesz do każdego z nich, a następnie zapisz je w osobnych, jak najprostszych obiektach DataFrame. Na tym etapie nie wykonuj analiz ani obliczeń statystycznych. Wykonaj jedynie podstawowe uporządkowanie danych: wybierz potrzebne kolumny, zadbaj o poprawne typy danych (np. data), usuń duplikaty oraz jednoznacznie oznacz brakujące wartości. Gotowe dane z obiektów DataFrame zapisz w osobnych plikach CSV.

### 4.1. Chcemy posiadać podstawowe informacje o lokalizacjach pomiarów pogodowych (stacje) oraz krajach, tak aby dane były zrozumiałe dla człowieka i możliwe do dalszego przetwarzania.

In [7]:
query = """
        SELECT usaf, wban, name, country, lat, lon, elev
        FROM `bigquery-public-data.noaa_gsod.stations`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df = df.drop_duplicates()
df.to_csv('data/zad4_1.csv', index=False)
df

,usaf,wban,name,country,lat,lon,elev
0,007018,None,WXPOD 7018,None,0.000,0.000,+7018.0
1,007026,None,WXPOD 7026,AF,0.000,0.000,+7026.0
2,007070,None,WXPOD 7070,AF,0.000,0.000,+7070.0
3,008268,None,WXPOD8278,AF,32.950,65.567,+1156.7
4,008307,None,WXPOD 8318,AF,0.000,0.000,+8318.0
...,...,...,...,...,...,...,...
29585,A06884,00416,LURAY CAVERNS AIRPORT,US,38.667,-78.501,+0275.2
29586,A07086,00468,CARL R KELLER FIELD AIRPORT,US,41.516,-82.869,+0179.8
29587,A51255,00445,DEMOPOLIS MUNICIPAL AIRPORT,US,32.464,-87.954,+0034.1
29588,A51256,00451,BRANSON WEST MUNICIPAL EMERSO,US,36.699,-93.402,+0411.2
29589,723629,53998,ORANGE COUNTY AIRPORT,US,30.069,-93.804,+0004.0

### 4.2. Chcemy wygenerować podstawowe zestawienia dotyczące warunków pogodowych na świecie (np. temperatura, opady, wiatr) w ujęciu dziennym.

In [8]:
query = """
        SELECT stn, wban, temp, dewp, slp, stp, visib, wdsp, prcp, sndp, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['temp'] = df['temp'].replace(9999.9, None).astype(np.float64)
df['dewp'] = df['dewp'].replace(9999.9, None).astype(np.float64)
df['slp'] = df['slp'].replace(9999.9, None).astype(np.float64)
df['stp'] = df['stp'].replace(9999.9, None).astype(np.float64)
df['visib'] = df['visib'].replace(999.9, None).astype(np.float64)
df['wdsp'] = df['wdsp'].replace('999.9', None).astype(np.float64)
df['prcp'] = df['prcp'].replace(99.99, None).astype(np.float64)
df['sndp'] = df['sndp'].replace(999.9, None).astype(np.float64)
df = df.drop_duplicates()

df.to_csv('data/zad4_2.csv', index=False)
df

,stn,wban,temp,dewp,slp,stp,visib,wdsp,prcp,sndp,date
0,010580,None,22.2,20.3,1009.7,962.2,NaN,9.9,0.0,NaN,2020-11-30
1,011330,None,28.8,24.7,NaN,999.9,NaN,4.7,0.0,NaN,2020-12-22
2,011980,None,54.4,43.2,1018.5,994.0,NaN,NaN,0.0,NaN,2020-09-02
3,012120,None,57.7,50.8,1002.7,1.0,NaN,39.4,0.0,NaN,2020-09-21
4,012900,None,39.6,39.2,NaN,999.9,6.2,4.5,0.0,NaN,2020-10-31
...,...,...,...,...,...,...,...,...,...,...,...
4119200,A51256,00451,47.3,43.7,NaN,974.2,8.6,5.6,0.0,NaN,2020-03-10
4119201,A51256,00451,24.2,17.6,NaN,984.7,10.0,7.2,0.0,NaN,2020-01-21
4119202,A51256,00451,76.8,73.0,NaN,953.9,7.0,9.8,NaN,NaN,2020-06-09
4119203,A51256,00451,39.5,33.5,NaN,968.0,6.3,3.7,0.0,NaN,2020-12-20
4119204,A51256,00451,81.7,73.0,NaN,967.6,9.9,3.3,NaN,NaN,2020-06-06

### 4.3. Chcemy poznać zjawiska ekstremalne w danych pogodowych poprzez uwypuklenie skrajnych wartości (np. bardzo wysokie/niskie temperatury, intensywne opady, silny wiatr).

In [9]:
query = """
        SELECT stn, wban, mxpsd, gust, max, min, prcp, snow_ice_pellets, hail, thunder, tornado_funnel_cloud, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['mxpsd'] = df['mxpsd'].replace('999.9', None).astype(np.float64)
df['gust'] = df['gust'].replace(999.9, None).astype(np.float64)
df['prcp'] = df['prcp'].replace(99.99, None).astype(np.float64)
df['max'] = df['max'].replace(9999.9, None).astype(np.float64)
df['min'] = df['min'].replace(9999.9, None).astype(np.float64)
df['snow_ice_pellets'] = df['snow_ice_pellets'].astype(np.int32).astype(np.bool)
df['hail'] = df['hail'].astype(np.int32).astype(np.bool)
df['thunder'] = df['thunder'].astype(np.int32).astype(np.bool)
df['tornado_funnel_cloud'] = df['tornado_funnel_cloud'].astype(np.int32).astype(np.bool)
df = df.drop_duplicates()

df.to_csv('data/zad4_3.csv', index=False)
df

,stn,wban,mxpsd,gust,max,min,prcp,snow_ice_pellets,hail,thunder,tornado_funnel_cloud,date
0,011440,None,22.0,33.0,51.1,46.4,0.00,False,False,False,False,2020-09-11
1,012880,None,7.0,20.6,39.0,22.5,0.00,False,False,False,False,2020-12-21
2,012900,None,6.0,NaN,39.2,37.0,0.00,False,False,False,False,2020-09-26
3,013520,None,17.5,NaN,32.2,16.9,0.00,False,False,False,False,2020-03-19
4,014240,None,NaN,NaN,45.5,31.6,0.02,False,False,False,False,2020-05-11
...,...,...,...,...,...,...,...,...,...,...,...,...
4119200,A51255,00445,9.9,NaN,92.3,70.3,0.00,False,False,False,False,2020-06-21
4119201,A51255,00445,4.1,NaN,68.0,35.4,0.00,False,False,False,False,2020-11-18
4119202,A51256,00451,12.0,20.0,75.2,64.4,NaN,False,False,True,False,2020-05-26
4119203,A51256,00451,9.9,15.9,82.4,66.2,0.00,False,False,False,False,2020-06-16
4119204,A51256,00451,11.1,15.0,84.2,64.4,0.00,False,False,False,False,2020-08-02

### 4.4. Chcemy przygotować dane umożliwiające analizę zmian warunków pogodowych w czasie (np. dla wybranych lokalizacji lub zmiennych).

In [10]:
query = """
        SELECT stn, wban, temp, dewp, stp, visib, wdsp, prcp, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['temp'] = df['temp'].replace(9999.9, None).astype(np.float64)
df['dewp'] = df['dewp'].replace(9999.9, None).astype(np.float64)
df['stp'] = df['stp'].replace(9999.9, None).astype(np.float64)
df['visib'] = df['visib'].replace(999.9, None).astype(np.float64)
df['wdsp'] = df['wdsp'].replace('999.9', None).astype(np.float64)
df['prcp'] = df['prcp'].replace(99.99, None).astype(np.float64)
df = df.drop_duplicates()

df.to_csv('data/zad4_4.csv', index=False)
df

            stn   wban  temp  dewp    stp  visib  wdsp  prcp        date
0        010460   None  27.2  20.4   12.6    NaN  11.1   0.0  2020-12-12
1        032145   None  77.0  56.3  999.9    6.2  12.0   0.0  2020-07-31
2        039084   None  56.3  45.1  999.9    6.2  17.8   0.0  2020-05-04
3        043410   None  15.6  -6.9   16.4    NaN  16.8   0.0  2020-11-17
4        085830   None  74.9  65.4  999.9   11.8  16.3   0.0  2020-04-02
...         ...    ...   ...   ...    ...    ...   ...   ...         ...
4119200  999999  94080  53.7   NaN  999.9    NaN   NaN   0.0  2020-09-10
4119201  999999  94645  69.0   NaN  999.9    NaN   NaN   0.0  2020-07-04
4119202  A00021  63884  62.8  57.5  959.4   10.0   NaN   0.0  2020-09-16
4119203  A00021  63884  70.7  63.9  951.3    6.9   NaN   NaN  2020-06-24
4119204  A00021  63884  79.6  70.8  956.3    8.8   NaN   0.0  2020-07-20

[4119205 rows x 9 columns]

### 4.5. Zdefiniuj własny dodatkowy przypadek związany z danymi pogodowymi.

#### Dane opisujące zjawiska pogodowe wpływające na poruszanie się samochodem

In [11]:
query = """
        SELECT stn, wban, visib, wdsp, mxpsd, gust, fog, hail, thunder, tornado_funnel_cloud, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['visib'] = df['visib'].replace(999.9, None).astype(np.float64)
df['wdsp'] = df['wdsp'].replace('999.9', None).astype(np.float64)
df['mxpsd'] = df['mxpsd'].replace('999.9', None).astype(np.float64)
df['gust'] = df['gust'].replace(999.99, None).astype(np.float64)

df['fog'] = df['fog'].astype(np.int32).astype(np.bool)
df['hail'] = df['hail'].astype(np.int32).astype(np.bool)
df['thunder'] = df['thunder'].astype(np.int32).astype(np.bool)
df['tornado_funnel_cloud'] = df['tornado_funnel_cloud'].astype(np.int32).astype(np.bool)
df = df.drop_duplicates()

df.to_csv('data/zad4_5.csv', index=False)
df

,stn,wban,visib,wdsp,mxpsd,gust,fog,hail,thunder,tornado_funnel_cloud,date
0,010350,None,NaN,NaN,NaN,999.9,False,False,False,False,2020-12-26
1,010420,None,NaN,10.3,15.5,999.9,False,False,False,False,2020-02-28
2,011390,None,NaN,12.2,13.0,16.9,False,False,False,False,2020-12-11
3,012770,None,NaN,6.4,10.5,25.4,False,False,False,False,2020-09-21
4,014033,None,NaN,16.1,17.5,19.0,False,False,False,False,2020-10-29
...,...,...,...,...,...,...,...,...,...,...,...
4119200,A07359,00240,10.0,4.3,11.1,17.1,False,False,False,False,2020-04-27
4119201,A51255,00445,9.9,1.9,8.0,999.9,False,False,False,False,2020-06-16
4119202,A51255,00445,10.0,3.7,12.0,15.9,False,False,False,False,2020-05-14
4119203,A51256,00451,10.0,4.8,14.0,22.9,False,False,False,False,2020-04-16
4119204,A51256,00451,10.0,5.7,11.1,18.1,False,False,False,False,2020-08-10

## Część 5

### Połącz ze sobą wszystkie dane otrzymane w części 4. Na ich podstawie utwórz jeden spójny zbiór danych i zapisz go jako oddzielny obiekt DataFrame. Jeżeli uznasz, że zasadne jest utworzenie więcej niż jednego zbioru, wykonaj to i uzasadnij swoją decyzję. Zadbaj o spójność struktury danych, w szczególności zgodność nazw kolumn, poprawność typów danych, brak duplikatów, jednoznaczne oznaczenie brakujących wartości. Wynik zapisz w pliku lub plikach CSV.

In [12]:
stations = pd.read_csv('data/zad4_1.csv')
pd.read_csv('data/zad4_2.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/daily_weather.csv', index=False)

pd.read_csv('data/zad4_3.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/extreme_weather.csv', index=False)

pd.read_csv('data/zad4_4.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/change_weather.csv', index=False)

pd.read_csv('data/zad4_5.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/car_weather.csv', index=False)

Uzasadnienie:
Uznaliśmy, że połączenie uzyskanych wcześniej zbiorów skutkowałoby dużym powieleniem danych. Zdecydowaliśmy się na połączenie każdego ze zbiorów zawierającego pomiary z informacją o ich lokalizacji.

## Część 6

### Połącz ze sobą dane otrzymane w części 5 oraz dane znajdujące się w dodatkowym pliku CSV zawierającym informacje o produkcji rolniczej.
Wybierz jedno z poniższych źródeł danych:

### 6.1  Dane FAOSTAT (zalecane)

Dane dotyczące produkcji rolniczej dostępne w bazie FAOSTAT: https://www.fao.org/faostat/en/#data/QCL

Dane obejmują m.in.:

Area – nazwa kraju

Item – rodzaj uprawy

Year – rok

Element – typ wartości (np. Production, Yield)

Value – wartość

#### Połącz dane pogodowe z danymi rolniczymi, zwracając szczególną uwagę na zgodność nazw krajów, dopasowanie zakresów czasowych, różnice w strukturze danych (np. dane dzienne vs roczne), brakujące wartości. Nowy zbiór danych zapisz jako oddzielny obiekt DataFrame. Jeżeli uważasz, że należy stworzyć kilka takich obiektów, zrób to i zapisz swoje uzasadnienie. Zadbaj o spójność struktury danych, w szczególności na zgodność nazw kolumn, poprawność typów danych, brak duplikatów, jednoznaczne oznaczenie brakujących wartości. Wynik tego zadania zapisz w pliku lub plikach CSV.

In [13]:
faostat = pd.read_csv('data_source/faostat_crops_and_livestock_products.csv').drop(columns=['Domain Code', 'Year', 'Domain', 'Note', 'Element Code', 'Item Code (CPC)', 'Year Code', 'Flag'])
faostat.columns = ['area_code', 'area_name', 'element', 'item', 'unit', 'value','flag_description']
faostat

,area_code,area_name,element,item,unit,value,flag_description
0,AF,Afghanistan,Area harvested,"Almonds, in shell",ha,22134.00,Official figure
1,AF,Afghanistan,Yield,"Almonds, in shell",kg/ha,1775.90,Official figure
2,AF,Afghanistan,Production,"Almonds, in shell",t,39307.00,Official figure
3,AF,Afghanistan,Area harvested,"Anise, badian, coriander, cumin, caraway, fenn...",ha,25558.00,Estimated value
4,AF,Afghanistan,Yield,"Anise, badian, coriander, cumin, caraway, fenn...",kg/ha,703.00,Estimated value
...,...,...,...,...,...,...,...
44914,ZW,Zimbabwe,Yield,Wheat,kg/ha,4779.60,Official figure
44915,ZW,Zimbabwe,Production,Wheat,t,212530.00,Official figure
44916,ZW,Zimbabwe,Production,Whole milk powder,t,5667.65,Value imputed by a receiving agency
44917,ZW,Zimbabwe,Production,"Whole milk, condensed",t,726.62,Value imputed by a receiving agency
44918,ZW,Zimbabwe,Production,"Whole milk, evaporated",t,4795.70,Value imputed by a receiving agency

In [14]:
weather= pd.read_csv('data/daily_weather.csv')
weather['date'] = pd.to_datetime(weather['date'])
weather['year'] = weather['date'].dt.year
year_weather = weather.groupby(['country', 'name', 'year']).agg(
    {
        'temp' : 'mean',
        'dewp' : 'mean',
        'slp' : 'mean',
        'stp' : 'mean',
        'visib' : 'mean',
        'wdsp' : 'mean',
        'prcp' : 'sum',
        'sndp': 'sum',
    }).reset_index()
year_weather.columns = ['country', 'station', 'year','yearly_mean_temp','yearly_mean_dewp','yearly_mean_slp','yearly_mean_stp','yearly_mean_visib','yearly_mean_wdsp','yearly_sum_prcp','yearly_sum_sndp']
merged_data = year_weather.merge(faostat, how='inner', left_on=['country'], right_on=['area_code']).drop(columns=['area_code','year'])
merged_data.to_csv('data/weather_faostat_annual.csv', index=False)
merged_data

/tmp/ipykernel_51229/4000552068.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  weather= pd.read_csv('data/daily_weather.csv')

,country,station,yearly_mean_temp,yearly_mean_dewp,yearly_mean_slp,yearly_mean_stp,yearly_mean_visib,yearly_mean_wdsp,yearly_sum_prcp,yearly_sum_sndp,area_name,element,item,unit,value,flag_description
0,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,"Almonds, in shell",ha,56.00,Official figure
1,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Yield,"Almonds, in shell",kg/ha,7857.10,Official figure
2,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Production,"Almonds, in shell",t,440.00,Official figure
3,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,Bananas,ha,14.00,Official figure
4,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Yield,Bananas,kg/ha,50000.00,Official figure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2882452,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,"Whey, dry",t,2956.53,Value imputed by a receiving agency
2882453,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Whole milk powder,t,6776.72,Value imputed by a receiving agency
2882454,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,"Whole milk, condensed",t,7495.78,Value imputed by a receiving agency
2882455,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,"Whole milk, evaporated",t,43687.94,Value imputed by a receiving agency
2882456,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Wine,t,1040000.00,Figure from external organization

In [15]:
weather= pd.read_csv('data/extreme_weather.csv')
weather['date'] = pd.to_datetime(weather['date'])
weather['year'] = weather['date'].dt.year
weather
year_weather = weather.groupby(['country', 'name', 'year']).agg({
    'mxpsd': 'max',
    'gust': 'max',
    'max': 'max',
    'min': 'min',
    'prcp': 'max',
    'snow_ice_pellets': 'sum',
    'hail': 'sum',
    'thunder': 'sum',
    'tornado_funnel_cloud': 'sum'
}).reset_index()
year_weather.columns = ['country', 'station_name', 'year', 'yearly_max_mxpd','yearly_max_gust','yearly_max_temp','yearly_min_temp','max_daily_prcp','days_with_snow','days_with_hail','days_with_thunder','days_with_tornado_funnel_cloud']
merged_data = year_weather.merge(faostat, how='inner', left_on=['country',], right_on=['area_code',]).drop(columns=['area_code','year'])
merged_data.to_csv('data/extreme_faostat_annual.csv', index=False)
merged_data

/tmp/ipykernel_51229/560492855.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  weather= pd.read_csv('data/extreme_weather.csv')

,country,station_name,yearly_max_mxpd,yearly_max_gust,yearly_max_temp,yearly_min_temp,max_daily_prcp,days_with_snow,days_with_hail,days_with_thunder,days_with_tornado_funnel_cloud,area_name,element,item,unit,value,flag_description
0,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,"Almonds, in shell",ha,56.00,Official figure
1,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Yield,"Almonds, in shell",kg/ha,7857.10,Official figure
2,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Production,"Almonds, in shell",t,440.00,Official figure
3,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,Bananas,ha,14.00,Official figure
4,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Yield,Bananas,kg/ha,50000.00,Official figure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2882452,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,"Whey, dry",t,2956.53,Value imputed by a receiving agency
2882453,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Whole milk powder,t,6776.72,Value imputed by a receiving agency
2882454,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,"Whole milk, condensed",t,7495.78,Value imputed by a receiving agency
2882455,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,"Whole milk, evaporated",t,43687.94,Value imputed by a receiving agency
2882456,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wine,t,1040000.00,Figure from external organization

## Część 7
### Misja dodatkowa - Więcej danych

#### Znajdź 3 dodatkowe zbiory danych, które w Twojej ocenie rozwijają temat wpływu warunków pogodowych na środowisko lub działalność człowieka. Mogą to być np. dane dotyczące rolnictwa (inne), środowiska, energii lub innych obszarów powiązanych z pogodą. Dla wybranych zbiorów wykonaj analogiczne czynności jak w części 4, tzn. przygotuj odpowiednie podzbiory danych w postaci obiektów DataFrame, bez wykonywania zaawansowanych analiz. Następnie połącz je z danymi otrzymanymi w części 6. Nowy zbiór danych zapisz jako oddzielny obiekt DataFrame. Jeżeli uważasz, że należy stworzyć kilka takich obiektów, zrób to i zapisz swoje uzasadnienie. Wynik tego zadania zapisz w pliku lub plikach CSV.

1. Value of Agricultural Production :https://www.fao.org/faostat/en/#data/QV

In [16]:
faostat = pd.read_csv('data_source/faostat_agricultural_production.csv').drop(columns=['Domain Code', 'Domain', 'Element Code', 'Item Code (CPC)', 'Year Code', 'Flag', 'Flag Description', 'Year'])

faostat = faostat[faostat['Unit'].str.contains('USD', na=False)].copy()
faostat = faostat[faostat['Element'].str.contains('current thousand', na=False)].copy()
faostat.columns = ['area_code', 'area_name', 'element', 'item', 'unit', 'value_1000_usd']
faostat = faostat.drop(columns=['element', 'area_name', 'unit'])

In [17]:
weather_merged = pd.read_csv('data/weather_faostat_annual.csv')
merged_data = weather_merged.merge(faostat, how='inner', left_on=['country','item'], right_on=['area_code','item']).drop(columns=['area_code'])
merged_data.to_csv('data/weather_agricultural_production_value.csv', index=False)
merged_data

,country,station,yearly_mean_temp,yearly_mean_dewp,yearly_mean_slp,yearly_mean_stp,yearly_mean_visib,yearly_mean_wdsp,yearly_sum_prcp,yearly_sum_sndp,area_name,element,item,unit,value,flag_description,value_1000_usd
0,AG,ABDENNIZI,76.612842,21.710656,NaN,999.9,NaN,8.215847,0.07,0.0,Antigua and Barbuda,Area harvested,Bananas,ha,11.0,Official figure,9
1,AG,ABDENNIZI,76.612842,21.710656,NaN,999.9,NaN,8.215847,0.07,0.0,Antigua and Barbuda,Yield,Bananas,kg/ha,415.9,Official figure,9
2,AG,ABDENNIZI,76.612842,21.710656,NaN,999.9,NaN,8.215847,0.07,0.0,Antigua and Barbuda,Production,Bananas,t,4.7,Official figure,9
3,AG,ABDENNIZI,76.612842,21.710656,NaN,999.9,NaN,8.215847,0.07,0.0,Antigua and Barbuda,Area harvested,Cabbages,ha,1.0,Official figure,4
4,AG,ABDENNIZI,76.612842,21.710656,NaN,999.9,NaN,8.215847,0.07,0.0,Antigua and Barbuda,Yield,Cabbages,kg/ha,1384.6,Official figure,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1656656,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.9,8.132471,5.955747,22.68,0.0,South Africa,Yield,Watermelons,kg/ha,16198.0,Estimated value,11623
1656657,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.9,8.132471,5.955747,22.68,0.0,South Africa,Production,Watermelons,t,60915.0,Official figure,11623
1656658,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.9,8.132471,5.955747,22.68,0.0,South Africa,Area harvested,Wheat,ha,509800.0,Official figure,626503
1656659,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.9,8.132471,5.955747,22.68,0.0,South Africa,Yield,Wheat,kg/ha,4158.5,Official figure,626503
1656660,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.9,8.132471,5.955747,22.68,0.0,South Africa,Production,Wheat,t,2120000.0,Official figure,626503

In [18]:
weather_merged = pd.read_csv('data/extreme_faostat_annual.csv')
merged_data = weather_merged.merge(faostat, how='inner', left_on=['country', 'item'], right_on=['area_code', 'item']).drop(columns=['area_code'])
merged_data.to_csv('data/extreme_agricultural_production_value.csv', index=False)
merged_data

,country,station_name,yearly_max_mxpd,yearly_max_gust,yearly_max_temp,yearly_min_temp,max_daily_prcp,days_with_snow,days_with_hail,days_with_thunder,days_with_tornado_funnel_cloud,area_name,element,item,unit,value,flag_description,value_1000_usd
0,AG,ABDENNIZI,34.0,NaN,109.9,28.8,0.02,0,0,0,0,Antigua and Barbuda,Area harvested,Bananas,ha,11.0,Official figure,9
1,AG,ABDENNIZI,34.0,NaN,109.9,28.8,0.02,0,0,0,0,Antigua and Barbuda,Yield,Bananas,kg/ha,415.9,Official figure,9
2,AG,ABDENNIZI,34.0,NaN,109.9,28.8,0.02,0,0,0,0,Antigua and Barbuda,Production,Bananas,t,4.7,Official figure,9
3,AG,ABDENNIZI,34.0,NaN,109.9,28.8,0.02,0,0,0,0,Antigua and Barbuda,Area harvested,Cabbages,ha,1.0,Official figure,4
4,AG,ABDENNIZI,34.0,NaN,109.9,28.8,0.02,0,0,0,0,Antigua and Barbuda,Yield,Cabbages,kg/ha,1384.6,Official figure,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1656656,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Yield,Watermelons,kg/ha,16198.0,Estimated value,11623
1656657,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Watermelons,t,60915.0,Official figure,11623
1656658,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Area harvested,Wheat,ha,509800.0,Official figure,626503
1656659,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Yield,Wheat,kg/ha,4158.5,Official figure,626503
1656660,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wheat,t,2120000.0,Official figure,626503

2. Pollution Emission from Crops: https://www.fao.org/faostat/en/#data/GCE

In [19]:
faostat = pd.read_csv('data_source/faostat_emission_from_crops.csv').drop(
    columns=['Domain Code', 'Domain', 'Element Code', 'Item Code (CPC)', 'Year Code','Year', 'Flag', 'Flag Description','Note','Source','Source Code'])
faostat = faostat[faostat['Unit'].str.contains('kt', na=False)].copy()
faostat.columns = ['area_code', 'area_name', 'emission_type', 'item', 'unit', 'value_kt']
faostat = faostat.drop(columns=['unit','area_name'])
faostat

     area_code                           emission_type          item  value_kt
1           AF           Crop residues (Emissions N2O)        Barley    0.0352
2           AF    Crop residues (Direct emissions N2O)        Barley    0.0287
3           AF  Crop residues (Indirect emissions N2O)        Barley    0.0065
5           AF           Crop residues (Emissions N2O)  Maize (corn)    0.0504
6           AF    Crop residues (Direct emissions N2O)  Maize (corn)    0.0412
...        ...                                     ...           ...       ...
6616        ZW           Crop residues (Emissions N2O)         Wheat    0.0513
6617        ZW    Crop residues (Direct emissions N2O)         Wheat    0.0419
6618        ZW  Crop residues (Indirect emissions N2O)         Wheat    0.0094
6620        ZW   Burning crop residues (Emissions N2O)         Wheat    0.0012
6621        ZW   Burning crop residues (Emissions CH4)         Wheat    0.0480

[4761 rows x 4 columns]

In [20]:
weather_merged = pd.read_csv('data/weather_faostat_annual.csv')
merged_data = weather_merged.merge(faostat, how='inner', left_on=['country','item'], right_on=['area_code','item']).drop(columns=['area_code',])
merged_data.to_csv('data/weather_pollution_emission.csv', index=False)
merged_data

,country,station,yearly_mean_temp,yearly_mean_dewp,yearly_mean_slp,yearly_mean_stp,yearly_mean_visib,yearly_mean_wdsp,yearly_sum_prcp,yearly_sum_sndp,area_name,element,item,unit,value,flag_description,emission_type,value_kt
0,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Crop residues (Emissions N2O),0.0039
1,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Crop residues (Direct emissions N2O),0.0032
2,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Crop residues (Indirect emissions N2O),0.0007
3,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Burning crop residues (Emissions N2O),0.0001
4,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Burning crop residues (Emissions CH4),0.0038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932884,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Wheat,t,2120000.0,Official figure,Crop residues (Emissions N2O),0.5165
932885,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Wheat,t,2120000.0,Official figure,Crop residues (Direct emissions N2O),0.4217
932886,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Wheat,t,2120000.0,Official figure,Crop residues (Indirect emissions N2O),0.0949
932887,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Wheat,t,2120000.0,Official figure,Burning crop residues (Emissions N2O),0.0143
932888,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Wheat,t,2120000.0,Official figure,Burning crop residues (Emissions CH4),0.5506

In [21]:
weather_merged = pd.read_csv('data/extreme_faostat_annual.csv')
merged_data = weather_merged.merge(faostat, how='inner', left_on=['country','item'], right_on=['area_code','item']).drop(columns=['area_code'])
merged_data.to_csv('data/extreme_pollution_emission.csv', index=False)
merged_data

,country,station_name,yearly_max_mxpd,yearly_max_gust,yearly_max_temp,yearly_min_temp,max_daily_prcp,days_with_snow,days_with_hail,days_with_thunder,days_with_tornado_funnel_cloud,area_name,element,item,unit,value,flag_description,emission_type,value_kt
0,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Crop residues (Emissions N2O),0.0039
1,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Crop residues (Direct emissions N2O),0.0032
2,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Crop residues (Indirect emissions N2O),0.0007
3,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Burning crop residues (Emissions N2O),0.0001
4,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,Maize (corn),ha,1391.0,Official figure,Burning crop residues (Emissions CH4),0.0038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932884,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wheat,t,2120000.0,Official figure,Crop residues (Emissions N2O),0.5165
932885,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wheat,t,2120000.0,Official figure,Crop residues (Direct emissions N2O),0.4217
932886,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wheat,t,2120000.0,Official figure,Crop residues (Indirect emissions N2O),0.0949
932887,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wheat,t,2120000.0,Official figure,Burning crop residues (Emissions N2O),0.0143
932888,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wheat,t,2120000.0,Official figure,Burning crop residues (Emissions CH4),0.5506

### Cost and Affordability of a Healthy Diet
https://www.fao.org/faostat/en/#data/CAHD

In [22]:
faostat = pd.read_csv('data_source/faostat_cahd.csv')\
    .drop(columns=['Domain Code', 'Domain', 'Element Code', 'Element', 'Item',
                   'Year Code','Year', 'Release', 'Flag', 'Flag Description'])
faostat = faostat[faostat['Item Code'] == 70040]  # USD per person per year
faostat = faostat.drop(columns=['Item Code','Unit', 'Area'])
faostat.columns = ['area_code', 'USD_ppp_year']

faostat

    area_code  USD_ppp_year
1          AL          3.40
3          DZ          4.19
5          AO          3.70
7          AG          4.67
9          AR           NaN
..        ...           ...
341        UY          3.45
343        UZ          3.97
345        VN          3.79
347        ZM          2.96
349        ZW           NaN

[175 rows x 2 columns]

In [23]:
weather_merged = pd.read_csv('data/weather_faostat_annual.csv')
merged_data = weather_merged.merge(faostat, how='inner', left_on=['country',], right_on=['area_code',]).drop(columns=['area_code',])
merged_data.to_csv('data/weather_cahd.csv', index=False)
merged_data

,country,station,yearly_mean_temp,yearly_mean_dewp,yearly_mean_slp,yearly_mean_stp,yearly_mean_visib,yearly_mean_wdsp,yearly_sum_prcp,yearly_sum_sndp,area_name,element,item,unit,value,flag_description,USD_ppp_year
0,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,"Almonds, in shell",ha,56.00,Official figure,2.85
1,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Yield,"Almonds, in shell",kg/ha,7857.10,Official figure,2.85
2,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Production,"Almonds, in shell",t,440.00,Official figure,2.85
3,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Area harvested,Bananas,ha,14.00,Official figure,2.85
4,AE,ABU DHABI INTL,84.090909,63.458678,1008.4825,270.069146,5.825344,7.530028,3.14,0.0,United Arab Emirates,Yield,Bananas,kg/ha,50000.00,Official figure,2.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2860825,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,"Whey, dry",t,2956.53,Value imputed by a receiving agency,3.00
2860826,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Whole milk powder,t,6776.72,Value imputed by a receiving agency,3.00
2860827,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,"Whole milk, condensed",t,7495.78,Value imputed by a receiving agency,3.00
2860828,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,"Whole milk, evaporated",t,43687.94,Value imputed by a receiving agency,3.00
2860829,ZA,LUSAKA INTL,70.623851,53.676437,NaN,999.900000,8.132471,5.955747,22.68,0.0,South Africa,Production,Wine,t,1040000.00,Figure from external organization,3.00

In [24]:
weather_merged = pd.read_csv('data/extreme_faostat_annual.csv')
merged_data = weather_merged.merge(faostat, how='inner', left_on=['country',], right_on=['area_code',]).drop(columns=['area_code',])
merged_data.to_csv('data/extreme_cahd.csv', index=False)
merged_data

,country,station_name,yearly_max_mxpd,yearly_max_gust,yearly_max_temp,yearly_min_temp,max_daily_prcp,days_with_snow,days_with_hail,days_with_thunder,days_with_tornado_funnel_cloud,area_name,element,item,unit,value,flag_description,USD_ppp_year
0,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,"Almonds, in shell",ha,56.00,Official figure,2.85
1,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Yield,"Almonds, in shell",kg/ha,7857.10,Official figure,2.85
2,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Production,"Almonds, in shell",t,440.00,Official figure,2.85
3,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Area harvested,Bananas,ha,14.00,Official figure,2.85
4,AE,ABU DHABI INTL,28.0,42.0,120.2,53.4,1.77,0,0,12,0,United Arab Emirates,Yield,Bananas,kg/ha,50000.00,Official figure,2.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2860825,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,"Whey, dry",t,2956.53,Value imputed by a receiving agency,3.00
2860826,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Whole milk powder,t,6776.72,Value imputed by a receiving agency,3.00
2860827,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,"Whole milk, condensed",t,7495.78,Value imputed by a receiving agency,3.00
2860828,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,"Whole milk, evaporated",t,43687.94,Value imputed by a receiving agency,3.00
2860829,ZA,LUSAKA INTL,31.1,58.3,98.6,41.5,2.68,0,0,59,0,South Africa,Production,Wine,t,1040000.00,Figure from external organization,3.00